Cadastro de Serviço
ricardobsilva/msmanager pull request #9
Opened 2022-04-26 00:59 UTC by wilmasilva-24

2022-04-26 01:00 UTC, wilmasilva-24 commented
PR de criação para formulário de serviço.

2022-04-27 01:59 UTC, ricardobsilva requested changes

2022-04-27 01:59 UTC, ricardobsilva commented on app/controllers/services_controller.rb
> +
Essa linha em branco aqui pode ser removida

2022-04-27 01:59 UTC, ricardobsilva commented on spec/controllers/services_controller_spec.rb
> +
Remover essa linha em branco

2022-04-27 01:59 UTC, ricardobsilva commented on spec/controllers/services_controller_spec.rb
> +
Remover essa linha em branco

2022-04-27 01:59 UTC, ricardobsilva commented on spec/controllers/services_controller_spec.rb
> +
Penso que seja interessante também testar se ele está renderizando o template correto (show)

2022-04-27 01:59 UTC, ricardobsilva commented on app/views/services/show.html.erb
> +
Essa linha em branco pode ser removida tb

2022-04-27 22:52 UTC, ricardobsilva approved these changes

2022-04-27 22:52 UTC, merged